### ISSUE TITLE
Cannot download asset from AssetLib

### ISSUE THREAD

**Issue by clutteroth** [GodotVR/godot_oculus_mobile#129]
The download link for version 3.0.1 in the Godot AssetLib appears to be broken:
https://godotengine.org/asset-library/asset/500
https://github.com/GodotVR/godot-oculus-mobile-asset/archive/d4a24127f38b80b0a05d8e4406cdcd51e2eb98bf.zip

**Comment by BastiaanOlij** [comment]
Looking into this, waiting for Akien or Calinou to have a look what I missed but I think they've gone to bed already :)

**Comment by akien-mga** [comment]
The URL is wrong, "godot_oculus_mobile" here but "godot-oculus-mobile" on the assetlib.

**Comment by BastiaanOlij** [comment]
> 
> 
> The URL is wrong, "godot_oculus_mobile" here but "godot-oculus-mobile" on the assetlib.

Just for future reference, the source repo is `godot_oculus_mobile`, the asset repo is `godot-oculus-mobile-asset`, so annoying we need to split that because we can't expose just a folder or the release zips in the asset library (hopefully some day soon).

For some reason it had the wrong commit string, I think the commit string was from the source repo while it should have the commit string from the mobile asset.

Should be correct now, @clutteroth can you check if you can download it properly now?

**Comment by clutteroth** [comment]
It's working now. Thank you!
