### ISSUE TITLE
GearVR oculus update required

### ISSUE THREAD

**Issue by muevoid** [GodotVR/godot_oculus_mobile#130]
I have been attempting to get this up and running for the gearvr to test it. I got the demo app building and chose 6dof Or 3dof for mode type and set hand tracking to optional. However when installing the app and running it. It starts but then says oculus update required and goes to oculus home. Any ideas?

**Comment by m4gr3d** [comment]
@muevoid The master branch uses the latest Oculus mobile sdk and as such it doesn't support `gear vr` as it's been  deprecated by Oculus.

There's an `oculus_go` branch made for that purpose so you could try that and see if that works.
Bear in mind that branch is no longer supported by us in order to focus our efforts, so we may accept pull requests for it, but we'd not be able to provide assistance/bug fixes ourselves.

**Comment by muevoid** [comment]
Thank you letting me know about the branch. Tested it out unfortunately does not seem to work just has a black screen I appreciate you trying to help though. Thanks!
