### ISSUE TITLE
Just a friendly reminder that the version in the asset store is still 3.0.1

### ISSUE THREAD

**Issue by BracerJack** [GodotVR/godot_oculus_mobile#135]
Just a friendly reminder that the version in the asset store is still 3.0.1.
Hopefully the person in charge will update it to the current version 3.1.0.

**Comment by BastiaanOlij** [comment]
@m4gr3d do we have a plan yet for releasing the current build?

**Comment by BastiaanOlij** [comment]
Btw @m4gr3d , on that subject, we changed both the OpenXR and OpenVR plugins so the CI builds a releasable zip file. It takes nudging Calinou to make some changes behind the scenes as only admins of the asset library can change the download link but it takes away the need to have a separate -asset repo, we should probably do the same here.

**Comment by BenMcLean** [comment]
I really appreciate all the work you guys do on these VR plugins!

I am on a super old version. Any changes I should make when upgrading?

Also, are there plans to make an OpenXR Android plugin so as to remove the dependency on Facebook? There is [at least one Android headset for consumers to compete with the Quest in the works](https://youtu.be/e7tnFtKvPPw) and they're saying it'll support OpenXR for its native apps at launch if I understand it right.

**Comment by BastiaanOlij** [comment]
@BenMcLean The latest version uses the new deployment with Android templates so you'll need to get familiar with that way of working and that files are placed in different places. We actually need a good write up of that process.

As for OpenXR, the problem at this point is that Android support is still not official for OpenXR.
Now Oculus did release an OpenXR runtime for Quest but it requires compiling their loader into our plugin. We'll likely start experimenting with that soon as the OpenXR runtime has now been released and is pretty stable on the other platforms.

The problem here is that OpenXR only supports the core features to initialize and interact with the headset and controllers, none of the Oculus specific features that you require to run something on the Quest so the first version will be limited compared to what the this native plugin does. The current line of thought is to split this plugin off into a platform specific plugin that adds all the support functions unique to the Quest.

So you'll use the OpenXR plugin for all the rendering, headset and controller logic, and then the platform plugin to make the Oculus eco system happy. That may seem convoluted but it also opens up the door to a lot of the other logic we've not looked into because they are an ill fit such as interacting with Oculus avatar system.

**Comment by m4gr3d** [comment]
@BastiaanOlij I've updated the oculus mobile asset github repo with the latest shared libraries: https://github.com/GodotVR/godot-oculus-mobile-asset/releases/tag/v3.3.0

So you should be able to update the asset store accordingly!

**Comment by BastiaanOlij** [comment]
Updated, just awaiting approval

**Comment by BracerJack** [comment]
Very exciting ! Just updated mine ! Thanks for the notification AND your hardwork !

**Comment by m4gr3d** [comment]
@BracerJack Just a reminder though that this'll be the last release for this plugin given the API it uses was deprecated by Meta.

Whenever possible I'd recommend evaluating migration to the Openxr plugin.

Let us know if you have any questions!
