### ISSUE TITLE
Sluggishness while running

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_oculus_mobile#26]
While running the demo on the oculus quest, as you look around, there is a noticeable latency, causing motion sickness

**Comment by creikey** [comment]
this is an issue with unit size and a lack of frame of reference it seems

**Comment by Schroedi** [comment]
I had the same problem on the quest. Can you check if you get late frames with the on device performance overlay? https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-ovrmetricstool/

If you get late frames, you could try my patch: https://github.com/GodotVR/godot_oculus_mobile/pull/24

**Comment by creikey** [comment]
@Schroedi Sure

**Comment by DEF7** [comment]
Just my two cents: in my experience with the PC Oculus SDK "LibOVR" the
tracking time that you receive from the API and pass back just before
rendering for the time/space warp stuff had some trick to it. I integrated
it into my engine and had the same problem. At the end of the day I had to
GetPredictedDisplayTime and GetTrackingState immediately after calling
BeginFrame - and generate my frame entirely off that. Then I had to pass
that time that I had received from the Oculus lib via
GetPredictedDisplayTime back into EndFrame in an EyeFovDepth layer so that
it knew how to properly extrapolate from the tracking state the frame was
generated at and the actual time that has since passed. Otherwise if you
pass the exact current time - and not when you sampled the tracking - it
will not extrapolate the rendered view with timewarp and feel like there's
1 entire frame of delay, which is huge for VR. I understand that a lot of
the LibOVR PC SDK API translates to the vrAPI mobile SDK's API for
GearVR/Go/Quest, so you shouldn't have a problem making sense of what I'm
talking about with the names of the functions I indicated here.

**Comment by creikey** [comment]
I'm reopening this as after continuous tweaking of various sizes of objects there is still a slugishness "off" feeling.

**Comment by creikey** [comment]
@Schroedi After trying your patch - #24 - I was still getting up to 70 stale frames averaging at about around 40, in contrast to the oculus home and every single other oculus demo app, which gets are 5 stale frames. It seems as if oculus quest godot vr support is just absolutely broken.

**Comment by creikey** [comment]
@DEF7 Yes, I believe that the oculus mobile sdk docs suggest doing just that, using the predicted display time sampled at when begin frame is called.

**Comment by Schroedi** [comment]
@DEF7, @creikey I think this is what the first commit in #24 does.
I took a look at my build again and discovered that I also enable the extra latency mode. If you have some time to test my update in #24, I would appreciate your feedback.

**Comment by creikey** [comment]
@Schroedi That line of code seems very strange, maybe adding a frame of latency helps the time warp?

**Comment by DEF7** [comment]
The Oculus documentation explains the situation with SwapInterval and ExtraLatency here: https://developer.oculus.com/documentation/quest/latest/concepts/mobile-vrapi/#mobile-vrapi

It is a contingency for programs which are unable to render frames quickly enough. Not necessarily framerate, just the actual time it takes from when the VrAPI returns control to the program to when it expects the finished frame to be submitted by so that it has enough time to perform its own work.

**Comment by m4gr3d** [comment]
Fixed by PR #24.

**Comment by esummers** [comment]
This appears to continue to be an issue on the Oculus Go in the latest dev build.  It is running a constant 60 fps, yet significant judder in the demo game.  I don't have a Quest to test with, but plan to pick one up next week.

**Comment by m4gr3d** [comment]
@esummers Which demo game are you referring to? And can you provide a dump of what OVR metrics reports on your device.

**Comment by esummers** [comment]
The demo included with godot_oculus_mobile.  I'm seeing the issue on the Oculus Quest and Oculus Go, but more pronounced on the Go.  FPS is constant 72 fps.  GPU Utilization is constantly at 99%.  GPU Level is constantly at 5 (not sure what this means since docs don't show a level above 4).  This is a very simple scene.  I wouldn't expect the GPU to be at a constant 99%.  This may just be an issue with using the 3.2 alpha release.
