### ISSUE TITLE
Controller tracking broken on oculus quest

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_oculus_mobile#31]
Controller tracking no longer works with the newest firmware update.

**Comment by m4gr3d** [comment]
@creikey Are you referring to the issue with only having one controller show up at a time on Quest?
If so, the fix for that issue is described [here](https://www.reddit.com/r/OculusQuest/comments/chjpu5/fix_for_sideloadedhomebrew_apps_and_games_with/) and I'll be pushing an update to the Godot engine to include it.

**Comment by creikey** [comment]
Ah yes, that's exactly the issue! It seems as if without that line in the android config, only one of the controllers works and there's only 3dof movement. I look forward to it being implemented in the Godot engine.

**Comment by creikey** [comment]
@m4gr3d I've opened an issue on godot here: https://github.com/godotengine/godot/issues/30854
