### ISSUE TITLE
Changing DOF in export settings breaks PanoramaSky

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_oculus_mobile#53]
On an oculus quest, when the DOF toggle is changed from `None` to `6DOF` or `3DOF and 6DOF`, the panorama sky is broken, extremely warped in the y axis.

**Comment by NeoSpark314** [comment]
Are you using GLES2 or GLES3? There was recently (~2 weeks ago) a fix for GLES2 in https://github.com/godotengine/godot/pull/32259
I just tested the demo application and it seems to work for me.

There were some build system changes for android. The final export template is now in godot/bin/android_debug.apk (or android_release.apk). Maybe you are still pointing to an old .apk where the fix was not yet applied?

Regarding the build system changes; I'm building now using something like
```
godot$ scons platform=android target=debug android_arch=arm64v8 -j12;
godot$ scons platform=android target=release android_arch=arm64v8 -j12;
godot/platform/android/java$ ./gradlew build -Pandroid_arch=arm64v8 -Pbuild_target=debug,release -Pj12
godot/platform/android/java$ ./gradlew generateGodotTemplates -Pandroid_arch=arm64v8 -Pbuild_target=debug,release
```

**Comment by creikey** [comment]
It turns out that I had an error in my build system, causing the android build templates to be about three months behind the current master. Apologies for the faulty issue.
