### ISSUE TITLE
OmniLights and Spotlights do not show on device

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_oculus_mobile#55]
OmniLights and SpotLights are invisible on the oculus quest, despite being visible in the editor. Example project attatched.
[vr-playground.zip](https://github.com/GodotVR/godot_oculus_mobile/files/3694243/vr-playground.zip)

**Comment by NeoSpark314** [comment]
I think the reason in your case is that by default in Project Settings -> Rendering -> Quality -> Shading for mobile the fallback for vertex lighting (and other fallbacks) are active. So with the big plane you have in the scene no vertex is in the area where you see the light. Turning off the settings for mobile should result in the expected behaviour and should look the same as in the editor:

![Screenshot from 2019-10-06 12-41-17](https://user-images.githubusercontent.com/1610621/66267832-a83da100-e836-11e9-9d9d-a8e069f37edd.png)

**Comment by creikey** [comment]
This solves the issue. Thanks!
