### ISSUE TITLE
Setup Instructions incomplete/not beginner friendly

### ISSUE THREAD

**Issue by Knochi** [GodotVR/godot_oculus_mobile#64]
When using the command line tools (CLT) the user will be confroted with a few problems.
- android SKD CLT doesn't come with cMake
- user has to use sdkmanager to install cmake
- sdk manager doesn't work with JAVA SE >10
- when trying to get Java SE 8 the user has to register at oracle (due to licensing)
- one way may be to use https://jdk.java.net/java-se-ri/10 but no idea how to install

When using Android Studio  there are a few missing steps
- user needs to install cmake through sdkmanager
- on windows platform cmake is in C:\Users\ _username_ \AppData\Local\Android\Sdk
- where is the `CMakeLists.txt`

**Comment by Luzzotica** [comment]
Yes I agree. 
Thank you so much for this, your extra steps and information helped me past a couple rough spots.

I would love to help improve the getting started portion of this library. I needs some help. The easier we can make it to get people on this, the more we can test it to ensure it is working properly.

I'll see what I can do about improving the tutorial as soon as I get this all working smoothly for myself.

Thank you for this!

**Comment by Luzzotica** [comment]
Deployment

When exporting the project apk in Godot, the following Android export Graphics options should be set:

- Xr Mode must be set to Oculus Mobile VR.
- Degrees of Freedom:
   1. If deploying only on Oculus Quest, this must be set to 6DOF
   2. If deploying on Oculus Go, or on Oculus Go and Oculus Quest, this must be set to 3DOF and 6DOF

I cannot seem to find the graphics option in the android export area. Am I looking in the wrong place? I have looked under settings as well. I can't seem to get this add-on to work and I am wondering if it is because of this. 
I am currently not trying to export the project, I am just trying to run it on my Go from Godot. Should I always export to run? Running from Godot is faster, but if it doesn't work I can export each time.

Definitely in need of some extra help here, thank you!

**Comment by NeoSpark314** [comment]
You can find the Xr Mode settings in the android export settings (Project -> Export):

![Screenshot from 2019-12-04 22-11-27](https://user-images.githubusercontent.com/1610621/70181978-3d4c0180-16e3-11ea-9200-94d147fce675.png)

Running it directly from godot should work without problems.

**Comment by BenMcLean** [comment]
> Degrees of Freedom:
> 
>     1. If deploying only on Oculus Quest, this must be set to 6DOF
> 
>     2. If deploying on Oculus Go, or on Oculus Go and Oculus Quest, this must be set to 3DOF and 6DOF

Actually, there is also a 3DOF mode available on the Oculus Quest. You can use it at night to watch movies in the dark! So make sure to allow 3DOF unless you have some really compelling reason not to.

**Comment by Luzzotica** [comment]
I must have set something up incorrectly then, because I do not have those options:

<img width="901" alt="Screen Shot 2019-12-05 at 7 18 51 PM" src="https://user-images.githubusercontent.com/32227368/70290098-18fc2d80-1794-11ea-9b74-f6282bf5cf2b.png">

What could cause this? Is the add-on supposed to create those options for me?
Sorry if this seems rather basic, I really appreciate the help. This might not be the place to ask. If there is something about add-ons that I am not fully understanding then I might need to go look and learn about those first.

Thank you for all the help!

**Comment by NeoSpark314** [comment]
Are you using a recent version of Godot 3.2? If not you could try the current beta-3: (https://godotengine.org/article/dev-snapshot-godot-3-2-beta-3)

**Comment by Luzzotica** [comment]
Yes, I just downloaded 3.2, thinking that that was my issue. It didn't resolve the problem. I will try a couple other things before I try moving to a beta version of Godot. I enjoy my stable releases. =)

I do feel like it should work with 3.1 though. Was this plugin not made starting for 3.1?

**Comment by NeoSpark314** [comment]
Yes; making it as easy as possible to use would be great. The plan is to have it precompiled on the asset library for 3.2 which should make the basic use very easy (https://github.com/GodotVR/godot-oculus-mobile-asset); compiling from source should then only be necessary when you need the recent master or in-development versions.
@m4gr3d also mentioned to start a wiki on this git for easier documentaiton. That might be a good way for you to add documentation or tips.
I'm also working on a gdscript toolkit to simplify the use of the Oculus Quest plugin and provide basic VR funcitoniality out of the box: https://github.com/NeoSpark314/godot_oculus_quest_toolkit

**Comment by Luzzotica** [comment]
Alright, I am working on making the setup instructions a little more clear and easy to follow.

I am curious about this line:
Note: Make sure you are using Android SDK's version of cmake.

Is this necessary? I just tested it with the most up to date version of CMake I can get and I was able to build everything normally.

I am on macOS Catalina.
CMake: 3.16.1
Everything works. But maybe this doesn't apply to maybe windows or linux?

**Comment by m4gr3d** [comment]
@Knochi @Luzzotica Can you give a try to the setup instructions for v2.0 of the plugin in [this branch](https://github.com/GodotVR/godot_oculus_mobile/tree/2.0).

While v2.0 is still in early development, the build process has been simplified so it may resolve some of the issues you're seeing.

**Comment by m4gr3d** [comment]
Fixed by PR #94
